services:
  - type: web
    name: Posty
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: bash -lc "python manage.py migrate && gunicorn myproject.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generate: secret
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_ALLOWED_HOSTS
        value: '*'
